## Sequential 모델

- Sequential 1:1 모델

In [ ]:
# 1. 데이터
# 1-7 훈련, 8-10 테스트, 11-13 예측
import numpy as np
x_train   = np.array([1,2,3,4,5,6,7,])
y_train   = np.array([1,2,3,4,5,6,7,])
x_test    = np.array([8,9,10])
y_test    = np.array([8,9,10])
x_predict = np.array([11,12,13])

# 2. 모델 구성
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(100, input_dim = 1, activation ='relu'))
model.add(Dense(30))
model.add(Dense(5))
model.add(Dense(1))

# 3. 훈련
# batch_size의 기본값은 16
model.compile(loss='mse', optimizer='adam', metrics=['mse'])
model.fit(x_train, y_train, epochs=100, batch_size=1, verbose=0)

# 4. 평가 예측
loss, mse = model.evaluate(x_test, y_test, batch_size=1)
print("mse : ", mse)
y_predict = model.predict(x_predict)
print("예측값 : \n", y_predict)

3/3 [==============================] - 0s 2ms/step - loss: 6.4301e-06 - mse: 6.4301e-06
mse :  6.430070698115742e-06
예측값 : 
 [[10.996179]
 [11.995506]
 [12.994834]]


- Sequential 다:다 모델

In [ ]:
# 1. 데이터
import numpy as np
x_train   = np.array([[1,2,3,4,5,6,7,], [11,12,13,14,15,16,17]])
y_train   = np.array([[1,2,3,4,5,6,7,], [11,12,13,14,15,16,17]])
x_test    = np.array([[8,9,10], [18,19,20]])
y_test    = np.array([[8,9,10], [18,19,20]])
x_predict = np.array([[21,22,23], [31,32,33]])
print(x_train.shape)
print(x_test.shape)
print(x_predict.shape)

x_train = np.transpose(x_train)
y_train = np.transpose(y_train)
x_test  = np.transpose(x_test)
y_test  = np.transpose(y_test)
x_predict = np.transpose(x_predict)
print(x_train.shape)
print(x_test.shape)
print(x_predict.shape)

# 2. 모델 구성
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(100, input_dim = 2, activation ='relu'))
model.add(Dense(30))
model.add(Dense(5))
model.add(Dense(2))

# 3. 훈련
model.compile(loss='mse', optimizer='adam', metrics=['mse'])
model.fit(x_train, y_train, epochs=100, batch_size=1, verbose=0)

# 4. 평가 예측
loss, mse = model.evaluate(x_test, y_test, batch_size=1)
print("mse : ", mse)

y_predict = model.predict(x_predict)
print("예측값 : \n", y_predict)

# 예측값 오차가 큼 -> 레이어와 노드의 개수 조절해 정확도를 높여야 함

(2, 7)
(2, 3)
(2, 3)
(7, 2)
(3, 2)
(3, 2)
3/3 [==============================] - 0s 2ms/step - loss: 0.1520 - mse: 0.1520
mse :  0.15197345614433289
예측값 : 
 [[16.710432 31.400866]
 [17.362207 32.444527]
 [18.013367 33.4878  ]]


- Sequential 다:1 모델

In [ ]:
# 1. 데이터
import numpy as np
x_train   = np.array([[1,2,3,4,5,6,7,], [11,12,13,14,15,16,17]])
y_train   = np.array([1,2,3,4,5,6,7,])
x_test    = np.array([[8,9,10], [18,19,20]])
y_test    = np.array([8,9,10])
x_predict = np.array([[21,22,23], [31,32,33]])
print('x_train.shape : ', x_train.shape)
print('y_train.shape : ', y_train.shape)
print('x_test.shape : ' , x_test.shape)
print('y_test.shape : ' , y_test.shape)
print('x_predict.shape : ', x_predict.shape )

x_train   = np.transpose(x_train)
x_test    = np.transpose(x_test)
x_predict = np.transpose(x_predict)
print('x_train.shape : ', x_train.shape)
print('y_train.shape : ', y_train.shape)
print('x_test.shape : ' , x_test.shape)
print('y_test.shape : ' , y_test.shape)
print('x_predict.shape : ', x_predict.shape )

# 2. 모델 구성
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(100, input_dim = 2, activation ='relu'))
model.add(Dense(30))
model.add(Dense(5))
model.add(Dense(1))

# 3. 훈련
model.compile(loss='mse', optimizer='adam', metrics=['mse'])
model.fit(x_train, y_train, epochs=100, batch_size=1, verbose=0)

# 4. 평가 예측
loss, mse = model.evaluate(x_test, y_test, batch_size=1)
print("mse : ", mse)
y_predict = model.predict(x_predict)
print("예측값 : \n", y_predict)

x_train.shape :  (2, 7)
y_train.shape :  (7,)
x_test.shape :  (2, 3)
y_test.shape :  (3,)
x_predict.shape :  (2, 3)
x_train.shape :  (7, 2)
y_train.shape :  (7,)
x_test.shape :  (3, 2)
y_test.shape :  (3,)
x_predict.shape :  (3, 2)
3/3 [==============================] - 0s 2ms/step - loss: 0.3693 - mse: 0.3693
mse :  0.3693087100982666
예측값 : 
 [[16.499128]
 [17.14275 ]
 [17.786367]]


- Sequential 1:다 모델

In [ ]:
# 1. 데이터
import numpy as np
x_train   = np.array([1,2,3,4,5,6,7,])
y_train   = np.array([[1,2,3,4,5,6,7,], [11,12,13,14,15,16,17]])
x_test    = np.array([8,9,10])
y_test    = np.array([[8,9,10], [18,19,20]])
x_predict = np.array([11,12,13])
print('x_train.shape : ', x_train.shape)
print('y_train.shape : ', y_train.shape)
print('x_test.shape : ' , x_test.shape)
print('y_test.shape : ' , y_test.shape)
print('x_predict.shape : ', x_predict.shape )

y_train = np.transpose(y_train)
y_test  = np.transpose(y_test)
print('x_train.shape : ', x_train.shape)
print('y_train.shape : ', y_train.shape)
print('x_test.shape : ' , x_test.shape)
print('y_test.shape : ' , y_test.shape)
print('x_predict.shape : ', x_predict.shape )

# 2. 모델 구성
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(100, input_dim = 1, activation ='relu'))
model.add(Dense(30))
model.add(Dense(5))
model.add(Dense(2))

# 3. 훈련
model.compile(loss='mse', optimizer='adam', metrics=['mse'])
model.fit(x_train, y_train, epochs=100, batch_size=1, verbose=0)

# 4. 평가 예측
loss, mse = model.evaluate(x_test, y_test, batch_size=1)
print("mse : ", mse)
y_predict = model.predict(x_predict)
print("예측값 : \n", y_predict)

x_train.shape :  (7,)
y_train.shape :  (2, 7)
x_test.shape :  (3,)
y_test.shape :  (2, 3)
x_predict.shape :  (3,)
x_train.shape :  (7,)
y_train.shape :  (7, 2)
x_test.shape :  (3,)
y_test.shape :  (3, 2)
x_predict.shape :  (3,)
3/3 [==============================] - 0s 2ms/step - loss: 2.5774 - mse: 2.5774
mse :  2.5774145126342773
예측값 : 
 [[ 9.687646  24.130013 ]
 [10.467529  25.674992 ]
 [11.2474165 27.219975 ]]


## 함수형 모델

- 함수형 1:1 모델

In [ ]:
# 1. 데이터
import numpy as np
x_train   = np.array([1,2,3,4,5,6,7,])
y_train   = np.array([1,2,3,4,5,6,7,])
x_test    = np.array([8,9,10])
y_test    = np.array([8,9,10])
x_predict = np.array([11,12,13])

# 2. 모델 구성
from keras.models import Model
from keras.layers import Dense, Input
input1  = Input(shape=(1,))
dense1  = Dense(100, activation='relu')(input1)
dense2  = Dense(30)(dense1)
dense3  = Dense(5)(dense2)
output1 = Dense(1)(dense3)
model   = Model(inputs = input1, outputs= output1)

# 3. 훈련
model.compile(loss='mse', optimizer='adam', metrics=['mse'])
model.fit(x_train, y_train, epochs=100, batch_size=1, verbose=0)

# 4. 평가 예측
loss, mse = model.evaluate(x_test, y_test, batch_size=1)
print("mse : ", mse)
y_predict = model.predict(x_predict)
print("예측값 : \n", y_predict)

3/3 [==============================] - 0s 2ms/step - loss: 8.9663e-06 - mse: 8.9663e-06
mse :  8.966319910541642e-06
예측값 : 
 [[10.995717]
 [11.995045]
 [12.994376]]


- 함수형 다:다 모델

In [ ]:
# 1. 데이터
import numpy as np
x_train   = np.array([[1,2,3,4,5,6,7,], [11,12,13,14,15,16,17]])
y_train   = np.array([[1,2,3,4,5,6,7,], [11,12,13,14,15,16,17]])
x_test    = np.array([[8,9,10], [18,19,20]])
y_test    = np.array([[8,9,10], [18,19,20]])
x_predict = np.array([[21,22,23], [31,32,33]])
print(x_train.shape)
print(x_test.shape)
print(x_predict.shape)

x_train   = np.transpose(x_train)
y_train   = np.transpose(y_train)
x_test    = np.transpose(x_test)
y_test    = np.transpose(y_test)
x_predict = np.transpose(x_predict)
print(x_train.shape)
print(x_test.shape)
print(x_predict.shape)

# 2. 모델 구성
from keras.models import Model
from keras.layers import Dense, Input
input1  = Input(shape=(2,))
dense1  = Dense(100, activation='relu')(input1)
dense2  = Dense(30)(dense1)
dense3  = Dense(5)(dense2)
output1 = Dense(2)(dense3)
model   = Model(inputs = input1, outputs= output1)

# 3. 훈련
model.compile(loss='mse', optimizer='adam', metrics=['mse'])
model.fit(x_train, y_train, epochs=100, batch_size=1, verbose=0)

# 4. 평가 예측
loss, mse = model.evaluate(x_test, y_test, batch_size=1)
print("mse : ", mse)

y_predict = model.predict(x_predict)
print("예측값 : \n", y_predict)

(2, 7)
(2, 3)
(2, 3)
(7, 2)
(3, 2)
(3, 2)
3/3 [==============================] - 0s 2ms/step - loss: 0.0572 - mse: 0.0572
mse :  0.05721372365951538
예측값 : 
 [[19.314142 32.485516]
 [20.194057 33.584503]
 [21.073977 34.683475]]


- 함수형 다:1 모델

In [ ]:
# 1. 데이터
import numpy as np
x_train = np.array([[1,2,3,4,5,6,7,], [11,12,13,14,15,16,17]])
y_train = np.array([1,2,3,4,5,6,7,])
x_test  = np.array([[8,9,10], [18,19,20]])
y_test    = np.array([8,9,10])
x_predict = np.array([[21,22,23], [31,32,33]])

print('x_train.shape : ', x_train.shape)
print('y_train.shape : ', y_train.shape)
print('x_test.shape : ' , x_test.shape)
print('y_test.shape : ' , y_test.shape)
print('x_predict.shape : ', x_predict.shape )

x_train   = np.transpose(x_train)
x_test    = np.transpose(x_test)
x_predict = np.transpose(x_predict)

print('x_train.shape : ', x_train.shape)
print('y_train.shape : ', y_train.shape)
print('x_test.shape : ' , x_test.shape)
print('y_test.shape : ' , y_test.shape)
print('x_predict.shape : ', x_predict.shape )

# 2. 모델 구성
from keras.models import Model
from keras.layers import Dense, Input
input1  = Input(shape=(2,))
dense1  = Dense(100, activation='relu')(input1)
dense2  = Dense(30)(dense1)
dense3  = Dense(5)(dense2)
output1 = Dense(1)(dense3)
model   = Model(inputs = input1, outputs= output1)

# 3. 훈련
model.compile(loss='mse', optimizer='adam', metrics=['mse'])
model.fit(x_train, y_train, epochs=100, batch_size=1, verbose=0)

# 4. 평가 예측
loss, mse = model.evaluate(x_test, y_test, batch_size=1)
print("mse : ", mse)
y_predict = model.predict(x_predict)
print("예측값 : \n", y_predict)

x_train.shape :  (2, 7)
y_train.shape :  (7,)
x_test.shape :  (2, 3)
y_test.shape :  (3,)
x_predict.shape :  (2, 3)
x_train.shape :  (7, 2)
y_train.shape :  (7,)
x_test.shape :  (3, 2)
y_test.shape :  (3,)
x_predict.shape :  (3, 2)
3/3 [==============================] - 0s 2ms/step - loss: 0.0512 - mse: 0.0512
mse :  0.05119122937321663
예측값 : 
 [[18.880304]
 [19.697393]
 [20.51389 ]]


- 함수형 1:다 모델

In [ ]:
# 1. 데이터
import numpy as np
x_train   = np.array([1,2,3,4,5,6,7,])
y_train   = np.array([[1,2,3,4,5,6,7,], [11,12,13,14,15,16,17]])
x_test    = np.array([8,9,10])
y_test    = np.array([[8,9,10], [18,19,20]])
x_predict = np.array([11,12,13])
print('x_train.shape : ', x_train.shape)
print('y_train.shape : ', y_train.shape)
print('x_test.shape : ' , x_test.shape)
print('y_test.shape : ' , y_test.shape)
print('x_predict.shape : ', x_predict.shape )

y_train = np.transpose(y_train)
y_test  = np.transpose(y_test)
print('x_train.shape : ', x_train.shape)
print('y_train.shape : ', y_train.shape)
print('x_test.shape : ' , x_test.shape)
print('y_test.shape : ' , y_test.shape)
print('x_predict.shape : ', x_predict.shape )

# 2. 모델 구성
from keras.models import Model
from keras.layers import Dense, Input
input1  = Input(shape=(1,))
dense1  = Dense(100, activation='relu')(input1)
dense2  = Dense(30)(dense1)
dense3  = Dense(5)(dense2)
output1 = Dense(2)(dense3)
model   = Model(inputs = input1, outputs= output1)

# 3. 훈련
model.compile(loss='mse', optimizer='adam', metrics=['mse'])
model.fit(x_train, y_train, epochs=100, batch_size=1, verbose=0)

# 4. 평가 예측
loss, mse = model.evaluate(x_test, y_test, batch_size=1)
print("mse : ", mse)
y_predict = model.predict(x_predict)
print("예측값 : \n", y_predict)

x_train.shape :  (7,)
y_train.shape :  (2, 7)
x_test.shape :  (3,)
y_test.shape :  (2, 3)
x_predict.shape :  (3,)
x_train.shape :  (7,)
y_train.shape :  (7, 2)
x_test.shape :  (3,)
y_test.shape :  (3, 2)
x_predict.shape :  (3,)
3/3 [==============================] - 0s 3ms/step - loss: 0.1705 - mse: 0.1705
mse :  0.1705407351255417
예측값 : 
 [[11.118548 21.865925]
 [12.14041  23.015974]
 [13.162269 24.166025]]


## 앙상블 및 기타 모델

- 앙상블 다:다 모델

In [ ]:
# 1. 데이터
import numpy as np
x1 = np.array([range(1, 101), range(101, 201)])
y1 = np.array([range(1, 101), range(101, 201)])
x2 = np.array([range(501, 601), range(601, 701)])
y2 = np.array([range(501, 601), range(601, 701)])

print(x1.shape)
print(x2.shape)
print(y1.shape)
print(y2.shape)

x1 = np.transpose(x1)
y1 = np.transpose(y1)
x2 = np.transpose(x2)
y2 = np.transpose(y2)

print(x1.shape)
print(x2.shape)
print(y1.shape)
print(y2.shape)

from sklearn.model_selection import train_test_split
x1_train, x1_test, y1_train, y1_test = train_test_split(x1, y1, random_state=66, test_size=0.2, shuffle = False)
x1_val, x1_test, y1_val, y1_test     = train_test_split(x1_test, y1_test, random_state=66, test_size=0.5, shuffle = False)
x2_train, x2_test, y2_train, y2_test = train_test_split(x2, y2, random_state=66, test_size=0.2, shuffle = False)
x2_val, x2_test, y2_val, y2_test     = train_test_split(x2_test, y2_test, random_state=66, test_size=0.5, shuffle = False)

print('x2_train.shape : ', x2_train.shape)
print('x2_val.shape : ', x2_val.shape)
print('x2_test.shape : ', x2_test.shape)

# 2. 모델 구성
from keras.models import Sequential, Model
from keras.layers import Dense, Input
input1 = Input(shape=(2,))
dense1 = Dense(100, activation='relu')(input1)
dense1 = Dense(30)(dense1)
dense1 = Dense(7)(dense1)

input2 = Input(shape=(2,))
dense2 = Dense(50, activation='relu')(input2)
dense2 = Dense(30)(dense2)
dense2 = Dense(7)(dense2)

from keras.layers.merge import concatenate
merge1  = concatenate([dense1, dense2])
middle1 = Dense(10)(merge1)
middle2 = Dense(5)(middle1)
middle3 = Dense(30)(middle2)

output1 = Dense(30)(middle3)
output1 = Dense(7)(output1)
output1 = Dense(2)(output1)

output2 = Dense(20)(middle3)
output2 = Dense(70)(output2)
output2 = Dense(2)(output2)

model = Model(inputs = [input1, input2],outputs = [output1, output2])
model.summary()

# 3. 훈련
model.compile(loss='mse', optimizer='adam', metrics=['mse'])
model.fit([x1_train, x2_train], [y1_train, y2_train], epochs=50, batch_size=1, validation_data=([x1_val, x2_val] , [y1_val, y2_val]), verbose=0)

#4. 평가 예측
mse = model.evaluate([x1_test, x2_test], [y1_test, y2_test], batch_size=1)
print("mse : ", mse)
y1_predict, y2_predict = model.predict([x1_test, x2_test])
print("y1 예측값 : \n", y1_predict, "\n y2 예측값 : \n", y2_predict)

(2, 100)
(2, 100)
(2, 100)
(2, 100)
(100, 2)
(100, 2)
(100, 2)
(100, 2)
x2_train.shape :  (80, 2)
x2_val.shape :  (10, 2)
x2_test.shape :  (10, 2)
Model: "functional_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 2)]          0                                            
__________________________________________________________________________________________________
input_2 (InputLayer)            [(None, 2)]          0                                            
__________________________________________________________________________________________________
dense (Dense)                   (None, 100)          300         input_1[0][0]                    
__________________________________________________________________________________________________
dense_3 (Dense)                 (None, 

- 앙상블 다:다 모델 2

In [ ]:
# 1. 데이터
import numpy as np
x1 = np.array([range(1, 101), range(101, 201)])
y1 = np.array([range(1, 101), range(101, 201)])
x2 = np.array([range(501, 601), range(601, 701)])
y2 = np.array([range(501, 601), range(601, 701)])
y3 = np.array([range(701, 801), range(801, 901)])

print(x1.shape)
print(x2.shape)
print(y1.shape)
print(y2.shape)
print(y3.shape)

x1 = np.transpose(x1)
y1 = np.transpose(y1)
x2 = np.transpose(x2)
y2 = np.transpose(y2)
y3 = np.transpose(y3)
print(x1.shape)
print(x2.shape)
print(y1.shape)
print(y2.shape)
print(y3.shape)

from sklearn.model_selection import train_test_split
x1_train, x1_test, y1_train, y1_test = train_test_split(x1, y1, random_state=66, test_size=0.2, shuffle = False)
x1_val,   x1_test, y1_val,   y1_test = train_test_split(x1_test, y1_test, random_state=66, test_size=0.5, shuffle = False)
x2_train, x2_test, y2_train, y2_test = train_test_split(x2, y2, random_state=66, test_size=0.2, shuffle = False)
x2_val,   x2_test, y2_val,   y2_test = train_test_split(x2_test, y2_test, random_state=66, test_size=0.5, shuffle = False)

#  y3 데이터의 분리
y3_train, y3_test = train_test_split(y3 , random_state=66, test_size=0.2, shuffle=False)
y3_val,   y3_test = train_test_split(y3_test , random_state=66, test_size=0.5, shuffle=False)

print('y3_train.shape :', y3_train.shape)
print('y3_val.shape :',   y3_val.shape)
print('y3_test.shape :',  y3_test.shape)

# 2. 모델 구성
from keras.models import Sequential, Model
from keras.layers import Dense, Input
input1 = Input(shape=(2,))
dense1 = Dense(100, activation='relu')(input1)
dense1 = Dense(30)(dense1)
dense1 = Dense(7)(dense1)

input2 = Input(shape=(2,))
dense2 = Dense(50, activation='relu')(input2)
dense2 = Dense(30)(dense2)
dense2 = Dense(7)(dense2)

from keras.layers.merge import concatenate
merge1  = concatenate([dense1, dense2])
middle1 = Dense(10)(merge1)
middle2 = Dense(5)(middle1)
middle3 = Dense(30)(middle2)

output1 = Dense(30)(middle3)
output1 = Dense(7)(output1)
output1 = Dense(2)(output1)

output2 = Dense(20)(middle3)
output2 = Dense(70)(output2)
output2 = Dense(2)(output2)

output3 = Dense(25)(middle3)
output3 = Dense(5)(output3)
output3 = Dense(2)(output3)

model = Model(inputs = [input1, input2], outputs = [output1, output2, output3])

#3. 훈련
model.compile(loss='mse', optimizer='adam', metrics=['mse'])
model.fit([x1_train, x2_train], [y1_train, y2_train, y3_train], epochs=50, batch_size=1, 
          validation_data=([x1_val, x2_val], [y1_val, y2_val, y3_val]), verbose=0)

#4. 평가 예측
mse = model.evaluate([x1_test, x2_test], [y1_test, y2_test, y3_test], batch_size=1)

y1_predict, y2_predict, y3_predict = model.predict([x1_test, x2_test])
print("y1 예측값 : \n", y1_predict, "\n y2 예측값 : \n", y2_predict, "\n y3 예측값 : \n", y3_predict)

(2, 100)
(2, 100)
(2, 100)
(2, 100)
(2, 100)
(100, 2)
(100, 2)
(100, 2)
(100, 2)
(100, 2)
y3_train.shape : (80, 2)
y3_val.shape : (10, 2)
y3_test.shape : (10, 2)
10/10 [==============================] - 0s 1ms/step - loss: 21.2408 - dense_26_loss: 12.1930 - dense_29_loss: 3.8690 - dense_32_loss: 5.1788 - dense_26_mse: 12.1930 - dense_29_mse: 3.8690 - dense_32_mse: 5.1788
y1 예측값 : 
 [[ 87.72522  189.5018  ]
 [ 88.50429  190.31508 ]
 [ 89.28329  191.12828 ]
 [ 90.06222  191.94156 ]
 [ 90.84124  192.75473 ]
 [ 91.62028  193.56801 ]
 [ 92.399216 194.38126 ]
 [ 93.178345 195.1945  ]
 [ 93.95725  196.00775 ]
 [ 94.73646  196.82101 ]] 
 y2 예측값 : 
 [[591.8833  693.05444]
 [592.8509  694.18744]
 [593.81866 695.3205 ]
 [594.78625 696.45374]
 [595.75385 697.5867 ]
 [596.7213  698.7197 ]
 [597.6891  699.85266]
 [598.6566  700.9857 ]
 [599.6242  702.11865]
 [600.59204 703.25195]] 
 y3 예측값 : 
 [[792.5768  892.92584]
 [793.61316 894.0899 ]
 [794.6495  895.2539 ]
 [795.68585 896.41785]
 [796.7222  897

- 앙상블 다:1 모델

In [ ]:
# 1. 데이터
import numpy as np
x1 = np.array([range(1, 101), range(101, 201)])
x2 = np.array([range(501, 601), range(601, 701)])
y  = np.array([range(1, 101), range(101, 201)])
print(x1.shape)
print(x2.shape)
print(y.shape)

x1 = np.transpose(x1)
x2 = np.transpose(x2)
y  = np.transpose(y)
print(x1.shape)
print(x2.shape)
print(y.shape)

from sklearn.model_selection import train_test_split
x1_train, x1_test, y_train, y_test = train_test_split(x1, y, random_state=66, test_size=0.2, shuffle = False)
x1_val,   x1_test, y_val,   y_test = train_test_split(x1_test, y_test, random_state=66, test_size=0.5, shuffle = False)
x2_train, x2_test                  = train_test_split(x2, random_state=66, test_size=0.2, shuffle = False)
x2_val,   x2_test                  = train_test_split(x2_test, random_state=66, test_size=0.5, shuffle = False)

print('x2_train.shape : ', x2_train.shape)
print('x2_val.shape : ', x2_val.shape)
print('x2_test.shape : ', x2_test.shape)

# 2. 모델 구성
from keras.models import Sequential, Model
from keras.layers import Dense, Input
input1 = Input(shape=(2,))
dense1 = Dense(100, activation='relu')(input1)
dense1 = Dense(30)(dense1)
dense1 = Dense(7)(dense1)

input2 = Input(shape=(2,))
dense2 = Dense(50, activation='relu')(input2)
dense2 = Dense(30)(dense2)
dense2 = Dense(7)(dense2)

from keras.layers.merge import concatenate
merge1 = concatenate([dense1, dense2])

output1 = Dense(30)(merge1)
output1 = Dense(7)(output1)
output1 = Dense(2)(output1)

model = Model(inputs = [input1, input2], outputs = output1)

# 3. 훈련
model.compile(loss='mse', optimizer='adam', metrics=['mse'])
model.fit([x1_train, x2_train], y_train, epochs=50, batch_size=1, validation_data=([x1_val, x2_val], y_val), verbose=0)

# 4. 평가 예측
mse = model.evaluate([x1_test, x2_test], y_test, batch_size=1)
print("mse : ", mse)

y_predict = model.predict([x1_test, x2_test])
print("y1 예측값 : \n", y_predict)

(2, 100)
(2, 100)
(2, 100)
(100, 2)
(100, 2)
(100, 2)
x2_train.shape :  (80, 2)
x2_val.shape :  (10, 2)
x2_test.shape :  (10, 2)
10/10 [==============================] - 0s 1ms/step - loss: 3.7065 - mse: 3.7065
mse :  [3.706537961959839, 3.706537961959839]
y1 예측값 : 
 [[ 89.11994  190.78601 ]
 [ 89.944756 191.76892 ]
 [ 90.76954  192.75189 ]
 [ 91.59423  193.73485 ]
 [ 92.416245 194.71912 ]
 [ 93.23825  195.70335 ]
 [ 94.06441  196.69032 ]
 [ 94.90336  197.68561 ]
 [ 95.74232  198.68095 ]
 [ 96.58126  199.67625 ]]


- 1:다 모델
  - 엄밀히 말하면 앙상블 모델 아님
  - 1개의 모델이 입력되어 여러 개의 모델로 나뉘어지는 분기 모델

In [ ]:
# 1. 데이터
import numpy as np
x  = np.array([range(1, 101), range(101, 201)])
y1 = np.array([range(501, 601), range(601, 701)])
y2 = np.array([range(1, 101), range(101, 201)])
print(x.shape)
print(y1.shape)
print(y2.shape)

x  = np.transpose(x)
y1 = np.transpose(y1)
y2 = np.transpose(y2)
print(x.shape)
print(y1.shape)
print(y2.shape)

from sklearn.model_selection import train_test_split
x_train,  x_test, y1_train, y1_test = train_test_split(x,      y1,      random_state=66, test_size=0.2, shuffle = False)
x_val,    x_test, y1_val,   y1_test = train_test_split(x_test, y1_test, random_state=66, test_size=0.5, shuffle = False)
y2_train, y2_test                   = train_test_split(y2,              random_state=66, test_size=0.2, shuffle = False)
y2_val,   y2_test                   = train_test_split(y2_test,         random_state=66, test_size=0.5, shuffle = False)

print('y2_train.shape : ', y2_train.shape)
print('y2_val.shape : ', y2_val.shape)
print('y2_test.shape : ', y2_test.shape)

# 2. 모델 구성
from keras.models import Sequential, Model
from keras.layers import Dense, Input
input1 = Input(shape=(2,))
dense1 = Dense(100, activation='relu')(input1)
dense1 = Dense(30)(dense1)
dense1 = Dense(7)(dense1)

output1 = Dense(30)(dense1)
output1 = Dense(7)(output1)
output1 = Dense(2)(output1)

output2 = Dense(30)(dense1)
output2 = Dense(7)(output1)
output2 = Dense(2)(output1)

model = Model(inputs = input1, outputs = [output1, output2])
model.summary()

# 3. 훈련
model.compile(loss='mse', optimizer='adam', metrics=['mse'])
model.fit(x_train, [y1_train, y2_train], epochs=50, batch_size=1, validation_data=(x_val, [y1_val, y2_val]), verbose=0)

# 4. 평가 예측
mse = model.evaluate(x_test, [y1_test, y2_test], batch_size=1)
print("mse : ", mse)
y1_predict, y2_predict = model.predict(x_test)
print("y1 예측값 : \n", y1_predict, "\n y2 예측값 : \n", y2_predict)

(2, 100)
(2, 100)
(2, 100)
(100, 2)
(100, 2)
(100, 2)
y2_train.shape :  (80, 2)
y2_val.shape :  (10, 2)
y2_test.shape :  (10, 2)
Model: "functional_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_7 (InputLayer)         [(None, 2)]               0         
_________________________________________________________________
dense_42 (Dense)             (None, 100)               300       
_________________________________________________________________
dense_43 (Dense)             (None, 30)                3030      
_________________________________________________________________
dense_44 (Dense)             (None, 7)                 217       
_________________________________________________________________
dense_45 (Dense)             (None, 30)                240       
_________________________________________________________________
dense_46 (Dense)             (None, 7)                 21