## MLP DNN 모델 (다:1)

In [ ]:
# 1. 데이터
import numpy as np
dataset = np.array([1,2,3,4,5,6,7,8,9,10])

def split_xy1(dataset, time_steps):
    x, y = list(), list()
    for i in range(len(dataset)):
        end_number = i + time_steps
        if end_number > len(dataset) -1:
            break
        tmp_x, tmp_y = dataset[i:end_number], dataset[end_number]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)
x, y = split_xy1(dataset, 4)
print(x, "\n", y)
print(x.shape)
print(y.shape)

# 2. 모델 구성
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(64, input_shape=(4, )))
model.add(Dense(1))

# 3. 훈련
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=1000, verbose=0)

# 4. 평가, 예측
mse = model.evaluate(x, y )
print("mse : ", mse)

x_pred = np.array([7, 8, 9, 10])
x_pred = x_pred.reshape(1, x_pred.shape[0])
print(x_pred.shape)

y_pred = model.predict(x_pred)
print(y_pred)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]] 
 [ 5  6  7  8  9 10]
(6, 4)
(6,)
1/1 [==============================] - 0s 1ms/step - loss: 0.0024
mse :  0.002358383499085903
(1, 4)
[[11.080078]]


## MLP RNN 모델 (다:1)

In [ ]:
# 1. 데이터
import numpy as np
dataset = np.array([1,2,3,4,5,6,7,8,9,10])
def split_xy1(dataset, time_steps):
    x, y = list(), list()
    for i in range(len(dataset)):
        end_number = i + time_steps
        if end_number > len(dataset) -1:
           break
        tmp_x, tmp_y = dataset[i:end_number], dataset[end_number]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

x, y = split_xy1(dataset, 4)
print(x, "\n", y)
print(x.shape)
print(y.shape)

x = x.reshape(x.shape[0], x.shape[1], 1)
print(x.shape)

# 2. 모델 구성
from keras.models import Sequential
from keras.layers import Dense, LSTM

model = Sequential()
model.add(LSTM(64, input_shape=(4, 1)))
model.add(Dense(1))

# 3. 훈련
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=1000, verbose=0)

# 4. 평가, 예측
mse = model.evaluate(x, y )
print("mse : ", mse)

x_pred = np.array([7, 8, 9, 10])
x_pred = x_pred.reshape(1, x_pred.shape[0], 1)
print(x_pred.shape)

y_pred = model.predict(x_pred)
print(y_pred)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]] 
 [ 5  6  7  8  9 10]
(6, 4)
(6,)
(6, 4, 1)
1/1 [==============================] - 0s 2ms/step - loss: 8.1256e-04
mse :  0.0008125637541525066
(1, 4, 1)
[[10.656176]]


## MLP RNN 모델 (다:다)

In [ ]:
# 1. 데이터
import numpy as np
dataset = np.array([1,2,3,4,5,6,7,8,9,10])

def split_xy2(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column
        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i : x_end_number]
        tmp_y = dataset[x_end_number : y_end_number]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

x, y = split_xy2(dataset, 4, 2)
print(x, "\n", y)
print(x.shape)
print(y.shape)
x = x.reshape(x.shape[0], x.shape[1], 1)
print(x.shape)

# 2. 모델 구성
from keras.models import Sequential
from keras.layers import Dense, LSTM

model = Sequential()
model.add(LSTM(64, input_shape=(4, 1)))
model.add(Dense(2))

# 3. 훈련
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=1000, verbose=0)

# 4. 평가, 예측
mse = model.evaluate(x, y )
print("mse : ", mse)

x_pred = np.array([6, 7, 8, 9])
x_pred = x_pred.reshape(1, x_pred.shape[0], 1)
y_pred = model.predict(x_pred)
print(y_pred)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]] 
 [[ 5  6]
 [ 6  7]
 [ 7  8]
 [ 8  9]
 [ 9 10]]
(5, 4)
(5, 2)
(5, 4, 1)
1/1 [==============================] - 0s 2ms/step - loss: 0.0015
mse :  0.0014886535936966538
[[ 9.633249 10.486404]]


## MLP RNN 모델 (다입력 다:1)

In [ ]:
# 1. 데이터
import numpy as np
dataset = np.array([[1,2,3,4,5,6,7,8,9,10],
                    [11,12,13,14,15,16,17,18,19,20],
                    [21,22,23,24,25,26,27,28,29,30]])
print("dataset.shape : ", dataset.shape)

dataset = np.transpose(dataset)
print(dataset)
print("dataset.shape : ", dataset.shape)

def split_xy3(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column -1
        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i:x_end_number, :-1]
        tmp_y = dataset[x_end_number-1:y_end_number, -1]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

x, y = split_xy3(dataset, 3, 1)
print(x, "\n", y)
print(x.shape)
print(y.shape)

y = y.reshape(y.shape[0])
print(y.shape)

# 2. 모델 구성
from keras.models import Sequential
from keras.layers import Dense, LSTM

model = Sequential()
model.add(LSTM(64, input_shape=(3, 2)))
model.add(Dense(1))

# 3. 훈련
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=300, batch_size=1, verbose=0)

# 4. 평가, 예측
mse = model.evaluate(x, y, batch_size=1 )
print("mse : ", mse)

x_pred = np.array([[9, 10, 11], [19, 20, 21]])
x_pred = np.transpose(x_pred)
x_pred = x_pred.reshape(1, x_pred.shape[0], x_pred.shape[1])
print(x_pred.shape)

y_pred = model.predict(x_pred, batch_size=1)
print(y_pred)

dataset.shape :  (3, 10)
[[ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]
 [10 20 30]]
dataset.shape :  (10, 3)
[[[ 1 11]
  [ 2 12]
  [ 3 13]]

 [[ 2 12]
  [ 3 13]
  [ 4 14]]

 [[ 3 13]
  [ 4 14]
  [ 5 15]]

 [[ 4 14]
  [ 5 15]
  [ 6 16]]

 [[ 5 15]
  [ 6 16]
  [ 7 17]]

 [[ 6 16]
  [ 7 17]
  [ 8 18]]

 [[ 7 17]
  [ 8 18]
  [ 9 19]]

 [[ 8 18]
  [ 9 19]
  [10 20]]] 
 [[23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]]
(8, 3, 2)
(8, 1)
(8,)
8/8 [==============================] - 0s 2ms/step - loss: 0.0042
mse :  0.004214064218103886
(1, 3, 2)
[[30.068113]]


## MLP DNN 모델 (다입력 다:1)

In [ ]:
# 1. 데이터
import numpy as np
dataset = np.array([[1,2,3,4,5,6,7,8,9,10],
                    [11,12,13,14,15,16,17,18,19,20],
                    [21,22,23,24,25,26,27,28,29,30]])
print("dataset.shape : ", dataset.shape)

dataset = np.transpose(dataset)
print(dataset)
print("dataset.shape : ", dataset.shape)

def split_xy3(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column -1 # 수정
        if y_end_number > len(dataset): # 수정
            break
        tmp_x = dataset[i:x_end_number, :-1]
        tmp_y = dataset[x_end_number-1:y_end_number, -1] # 수정
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

x, y = split_xy3(dataset, 3, 1)
print(x, "\n", y)
print(x.shape)
print(y.shape)

y = y.reshape(y.shape[0])
print(y.shape)

x = x.reshape(x.shape[0], x.shape[1] * x.shape[2])
print(x.shape)

# 2. 모델 구성
from keras.models import Sequential
from keras.layers import Dense, LSTM

model = Sequential()
model.add(Dense(64, input_shape=(6, )))
model.add(Dense(1))

# 3. 훈련
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=300, batch_size=1, verbose=0)

# 4. 평가, 예측
mse = model.evaluate(x, y, batch_size=1 )
print("mse : ", mse)

x_pred = np.array([[9, 10, 11], [19, 20, 21]])
print(x_pred.shape)

x_pred = x_pred.reshape(1, x_pred.shape[0] * x_pred.shape[1])
print(x_pred.shape)

y_pred = model.predict(x_pred, batch_size=1)
print(y_pred)

dataset.shape :  (3, 10)
[[ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]
 [10 20 30]]
dataset.shape :  (10, 3)
[[[ 1 11]
  [ 2 12]
  [ 3 13]]

 [[ 2 12]
  [ 3 13]
  [ 4 14]]

 [[ 3 13]
  [ 4 14]
  [ 5 15]]

 [[ 4 14]
  [ 5 15]
  [ 6 16]]

 [[ 5 15]
  [ 6 16]
  [ 7 17]]

 [[ 6 16]
  [ 7 17]
  [ 8 18]]

 [[ 7 17]
  [ 8 18]
  [ 9 19]]

 [[ 8 18]
  [ 9 19]
  [10 20]]] 
 [[23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]]
(8, 3, 2)
(8, 1)
(8,)
(8, 6)
8/8 [==============================] - 0s 2ms/step - loss: 7.4579e-11
mse :  7.457856554538012e-11
(2, 3)
(1, 6)
[[20.881306]]


## MLP DNN 모델 (다입력 다:다)

In [ ]:
# 1. 데이터
import numpy as np
dataset = np.array([[1,2,3,4,5,6,7,8,9,10], 
                    [11,12,13,14,15,16,17,18,19,20],
                    [21,22,23,24,25,26,27,28,29,30]])
print("dataset.shape : ", dataset.shape)

dataset = np.transpose(dataset)
print(dataset)
print("dataset.shape : ", dataset.shape)

def split_xy3(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column -1
        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i:x_end_number, :-1]
        tmp_y = dataset[x_end_number-1:y_end_number, -1]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

x, y = split_xy3(dataset, 3, 2)
print(x.shape)
print(y.shape)

# 2. 모델 구성
from keras.models import Sequential
from keras.layers import Dense, LSTM

model = Sequential()
model.add(LSTM(64, input_shape=(3, 2)))
model.add(Dense(2))

# 3. 훈련
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=300, batch_size=1, verbose=0)

# 4. 평가, 예측
mse = model.evaluate(x, y, batch_size=1 )
print("mse : ", mse)

x_pred = np.array([[9, 10, 11], [19, 20, 21]])
x_pred = np.transpose(x_pred)
x_pred = x_pred.reshape(1, x_pred.shape[0], x_pred.shape[1])

y_pred = model.predict(x_pred, batch_size=1)
print(y_pred)

dataset.shape :  (3, 10)
[[ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]
 [10 20 30]]
dataset.shape :  (10, 3)
(7, 3, 2)
(7, 2)
7/7 [==============================] - 0s 1ms/step - loss: 0.0118
mse :  0.011780682019889355
[[28.912365 29.990562]]


## MLP DNN 모델 (다입력 다:다)

In [ ]:
# 1. 데이터
import numpy as np
dataset = np.array([[1,2,3,4,5,6,7,8,9,10],
                   [11,12,13,14,15,16,17,18,19,20],
                   [21,22,23,24,25,26,27,28,29,30]])
print("dataset.shape : ", dataset.shape)

dataset = np.transpose(dataset)
print(dataset)
print("dataset.shape : ", dataset.shape)

def split_xy3(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column -1
        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i:x_end_number, :-1]
        tmp_y = dataset[x_end_number-1:y_end_number, -1]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

x, y = split_xy3(dataset, 3, 2)
print(x.shape)
print(y.shape)

x = x.reshape(x.shape[0], x.shape[1] * x.shape[2])
print(x.shape)

# 2. 모델 구성
from keras.models import Sequential
from keras.layers import Dense, LSTM

model = Sequential()
model.add(Dense(64, input_shape=(6, )))
model.add(Dense(2))

# 3. 훈련
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=300, batch_size=1, verbose=0)

# 4. 평가, 예측
mse = model.evaluate(x, y, batch_size=1 )
print("mse : ", mse)

x_pred = np.array([[9, 10, 11], [19, 20, 21]])
x_pred = np.transpose(x_pred)
x_pred = x_pred.reshape(1, x_pred.shape[0] * x_pred.shape[1])
print(x_pred.shape)

y_pred = model.predict(x_pred, batch_size=1)
print(y_pred)

dataset.shape :  (3, 10)
[[ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]
 [10 20 30]]
dataset.shape :  (10, 3)
(7, 3, 2)
(7, 2)
(7, 6)
7/7 [==============================] - 0s 2ms/step - loss: 2.1074e-10
mse :  2.1074290923461803e-10
(1, 6)
[[31.000036 32.000034]]


## RNN 모델 (다입력 다:다 두 번째)

In [ ]:
# 1. 데이터
import numpy as np
dataset = np.array([[1,2,3,4,5,6,7,8,9,10],
                    [11,12,13,14,15,16,17,18,19,20],    
                    [21,22,23,24,25,26,27,28,29,30]])
print("dataset.shape : ", dataset.shape)

dataset = np.transpose(dataset)
print(dataset)
print("dataset.shape : ", dataset.shape)

def split_xy5(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column
        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i:x_end_number, :]
        tmp_y = dataset[x_end_number:y_end_number, :]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

x, y = split_xy5(dataset, 3, 1)
print(x, "\n", y)
print(x.shape)
print(y.shape)

y = y.reshape(y.shape[0], y.shape[2])
print(y.shape)

# 2. 모델 구성
from keras.models import Sequential
from keras.layers import Dense, LSTM

model = Sequential()
model.add(LSTM(64, input_shape=(3, 3)))
model.add(Dense(3))

# 3. 훈련
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=300, batch_size=1, verbose=0)

# 4. 평가, 예측
mse = model.evaluate(x, y, batch_size=1 )
print("mse : ", mse)

x_pred = np.array([[8, 9, 10],[18, 19, 20], [28, 29, 30]])
x_pred = np.transpose(x_pred)
x_pred = x_pred.reshape(1, x_pred.shape[0], x_pred.shape[1])
print(x_pred)
print(x_pred.shape)

y_pred = model.predict(x_pred, batch_size=1)
print(y_pred)

dataset.shape :  (3, 10)
[[ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]
 [10 20 30]]
dataset.shape :  (10, 3)
[[[ 1 11 21]
  [ 2 12 22]
  [ 3 13 23]]

 [[ 2 12 22]
  [ 3 13 23]
  [ 4 14 24]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]

 [[ 4 14 24]
  [ 5 15 25]
  [ 6 16 26]]

 [[ 5 15 25]
  [ 6 16 26]
  [ 7 17 27]]

 [[ 6 16 26]
  [ 7 17 27]
  [ 8 18 28]]

 [[ 7 17 27]
  [ 8 18 28]
  [ 9 19 29]]] 
 [[[ 4 14 24]]

 [[ 5 15 25]]

 [[ 6 16 26]]

 [[ 7 17 27]]

 [[ 8 18 28]]

 [[ 9 19 29]]

 [[10 20 30]]]
(7, 3, 3)
(7, 1, 3)
(7, 3)
7/7 [==============================] - 0s 1ms/step - loss: 0.0102
mse :  0.010212925262749195
[[[ 8 18 28]
  [ 9 19 29]
  [10 20 30]]]
(1, 3, 3)
[[10.268292 20.145947 29.968168]]


## DNN 모델 (다입력 다:다 두 번째)

In [ ]:
# 1. 데이터
import numpy as np
dataset = np.array([[1,2,3,4,5,6,7,8,9,10],
                    [11,12,13,14,15,16,17,18,19,20],    
                    [21,22,23,24,25,26,27,28,29,30]])
print("dataset.shape : ", dataset.shape)

dataset = np.transpose(dataset)
print(dataset)
print("dataset.shape : ", dataset.shape)

def split_xy5(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column
        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i:x_end_number, :]
        tmp_y = dataset[x_end_number:y_end_number, :]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

x, y = split_xy5(dataset, 3, 1)
print(x, "\n", y)
print(x.shape)
print(y.shape)

y = y.reshape(y.shape[0], y.shape[2])
print(y.shape)

x = x.reshape(x.shape[0], x.shape[1] * x.shape[2])
print(x.shape)

# 2. 모델 구성
from keras.models import Sequential
from keras.layers import Dense, LSTM

model = Sequential()
model.add(Dense(64, input_shape=(9,)))
model.add(Dense(3))

# 3. 훈련
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=300, batch_size=1, verbose=0)

# 4. 평가, 예측
mse = model.evaluate(x, y, batch_size=1 )
print("mse : ", mse)

x_pred = np.array([[8, 9, 10],[18, 19, 20], [28, 29, 30]])
x_pred = np.transpose(x_pred)
x_pred = x_pred.reshape(1, x_pred.shape[0] * x_pred.shape[1]) # 수정
print(x_pred)
print(x_pred.shape)

y_pred = model.predict(x_pred, batch_size=1)
print(y_pred)

dataset.shape :  (3, 10)
[[ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]
 [10 20 30]]
dataset.shape :  (10, 3)
[[[ 1 11 21]
  [ 2 12 22]
  [ 3 13 23]]

 [[ 2 12 22]
  [ 3 13 23]
  [ 4 14 24]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]

 [[ 4 14 24]
  [ 5 15 25]
  [ 6 16 26]]

 [[ 5 15 25]
  [ 6 16 26]
  [ 7 17 27]]

 [[ 6 16 26]
  [ 7 17 27]
  [ 8 18 28]]

 [[ 7 17 27]
  [ 8 18 28]
  [ 9 19 29]]] 
 [[[ 4 14 24]]

 [[ 5 15 25]]

 [[ 6 16 26]]

 [[ 7 17 27]]

 [[ 8 18 28]]

 [[ 9 19 29]]

 [[10 20 30]]]
(7, 3, 3)
(7, 1, 3)
(7, 3)
(7, 9)
7/7 [==============================] - 0s 1ms/step - loss: 1.3439e-11
mse :  1.3439408440285572e-11
[[ 8 18 28  9 19 29 10 20 30]]
(1, 9)
[[11.000003 21.000004 31.000015]]


## RNN 모델 (다입력 다:다 세 번째)

In [ ]:
# 1. 데이터
import numpy as np
dataset = np.array([[1,2,3,4,5,6,7,8,9,10],
                    [11,12,13,14,15,16,17,18,19,20],
                    [21,22,23,24,25,26,27,28,29,30]])
print("dataset.shape : ", dataset.shape)

dataset = np.transpose(dataset)
print(dataset)
print("dataset.shape : ", dataset.shape)

def split_xy5(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column # 수정
        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i:x_end_number, :] # 수정
        tmp_y = dataset[x_end_number:y_end_number, :] # 수정
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

x, y = split_xy5(dataset, 3, 2)
print(x, "\n", y)
print(x.shape)
print(y.shape)

y = y.reshape(y.shape[0], y.shape[1] * y.shape[2])
print(y.shape)

# 2. 모델 구성
from keras.models import Sequential
from keras.layers import Dense, LSTM

model = Sequential()
model.add(LSTM(64, input_shape=(3, 3)))
model.add(Dense(6))

# 3. 훈련
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=300, batch_size=1, verbose=0)

# 4. 평가, 예측
mse = model.evaluate(x, y, batch_size=1 )
print("mse : ", mse)

x_pred = np.array([[8, 9, 10],[18, 19, 20], [28, 29, 30]])
x_pred = np.transpose(x_pred)
x_pred = x_pred.reshape(1, x_pred.shape[0], x_pred.shape[1])

y_pred = model.predict(x_pred, batch_size=1)
print(y_pred)

dataset.shape :  (3, 10)
[[ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]
 [10 20 30]]
dataset.shape :  (10, 3)
[[[ 1 11 21]
  [ 2 12 22]
  [ 3 13 23]]

 [[ 2 12 22]
  [ 3 13 23]
  [ 4 14 24]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]

 [[ 4 14 24]
  [ 5 15 25]
  [ 6 16 26]]

 [[ 5 15 25]
  [ 6 16 26]
  [ 7 17 27]]

 [[ 6 16 26]
  [ 7 17 27]
  [ 8 18 28]]] 
 [[[ 4 14 24]
  [ 5 15 25]]

 [[ 5 15 25]
  [ 6 16 26]]

 [[ 6 16 26]
  [ 7 17 27]]

 [[ 7 17 27]
  [ 8 18 28]]

 [[ 8 18 28]
  [ 9 19 29]]

 [[ 9 19 29]
  [10 20 30]]]
(6, 3, 3)
(6, 2, 3)
(6, 6)
6/6 [==============================] - 0s 3ms/step - loss: 0.0305
mse :  0.030453607439994812
[[ 8.81975  18.948683 28.72438  10.002936 19.99532  29.826054]]


## DNN 모델 (다입력 다:다 세 번째)

In [ ]:
# 1. 데이터
import numpy as np
dataset = np.array([[1,2,3,4,5,6,7,8,9,10],
                   [11,12,13,14,15,16,17,18,19,20],
                   [21,22,23,24,25,26,27,28,29,30]])
print("dataset.shape : ", dataset.shape)

dataset = np.transpose(dataset)
print(dataset)
print("dataset.shape : ", dataset.shape)

def split_xy5(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column # 수정
        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i:x_end_number, :] # 수정
        tmp_y = dataset[x_end_number:y_end_number, :] # 수정
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

x, y = split_xy5(dataset, 3, 2)

x = x.reshape(x.shape[0], x.shape[1] * x.shape[2])
print(x.shape)

y = y.reshape(y.shape[0], y.shape[1] * y.shape[2])
print(y.shape)

# 2. 모델 구성
from keras.models import Sequential
from keras.layers import Dense, LSTM
model = Sequential()
model.add(Dense(64, input_shape=(9, )))
model.add(Dense(6))

# 3. 훈련
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=300, batch_size=1, verbose=0)

# 4. 평가, 예측
mse = model.evaluate(x, y, batch_size=1 )
print("mse : ", mse)

x_pred = np.array([[8, 9, 10],[18, 19, 20], [28, 29, 30]])
x_pred = np.transpose(x_pred)
x_pred = x_pred.reshape(1, x_pred.shape[0] * x_pred.shape[1])
print(x_pred)
print(x_pred.shape)

y_pred = model.predict(x_pred, batch_size=1)
print(y_pred)

dataset.shape :  (3, 10)
[[ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]
 [10 20 30]]
dataset.shape :  (10, 3)
(6, 9)
(6, 6)
6/6 [==============================] - 0s 2ms/step - loss: 4.9747e-07
mse :  4.974650096301048e-07
[[ 8 18 28  9 19 29 10 20 30]]
(1, 9)
[[11.000235 21.0022   31.002085 12.000223 22.000957 32.001892]]
