## 데이터 저장

In [ ]:
import numpy as np
import pandas as pd

df1 = pd.read_csv("/content/drive/My Drive/Prediction of Time Series Walking in Deep Learning/data/kospi200.csv", index_col=0, 
                  header=0, encoding='cp949', sep=',')
             
print(df1)
print(df1.shape)

                시가      고가      저가     현재가      거래량
일자                                                 
2020-01-31  290.24  291.47  284.53  284.53  101,455
2020-01-30  293.27  294.11  287.09  288.37  101,535
2020-01-29  294.38  295.67  292.45  293.98   85,731
2020-01-28  294.98  296.30  291.30  292.77  130,172
2020-01-23  303.77  304.72  301.71  302.33   86,908
...            ...     ...     ...     ...      ...
2018-05-11  318.03  319.70  317.86  318.51  112,400
2018-05-10  316.51  317.34  315.11  317.31  120,900
2018-05-09  315.93  316.08  312.60  314.42  123,610
2018-05-08  317.79  319.53  314.95  315.87  141,252
2018-05-04  320.56  321.00  316.75  316.75  173,911

[426 rows x 5 columns]
(426, 5)


In [ ]:
df2 = pd.read_csv("/content/drive/My Drive/Prediction of Time Series Walking in Deep Learning/data/samsung.csv", index_col=0, 
                  header=0, encoding='cp949', sep=',')   

print(df2)
print(df2.shape)

                시가      고가      저가      종가         거래량
일자                                                    
2020-01-31  57,800  58,400  56,400  56,400  19,749,457
2020-01-30  58,800  58,800  56,800  57,200  20,821,939
2020-01-29  59,100  59,700  58,800  59,100  16,446,102
2020-01-28  59,400  59,400  58,300  58,800  23,664,541
2020-01-23  61,800  61,800  60,700  60,800  14,916,555
...            ...     ...     ...     ...         ...
2018-05-11  52,000  52,200  51,200  51,300  10,314,997
2018-05-10  51,700  51,700  50,600  51,600  13,905,263
2018-05-09  52,600  52,800  50,900  50,900  16,128,305
2018-05-08  52,600  53,200  51,900  52,600  23,104,720
2018-05-04  53,000  53,900  51,800  51,900  39,565,391

[426 rows x 5 columns]
(426, 5)


In [ ]:
# kospi200의 거래량
for i in range(len(df1.index)):     # 거래량 str -> int 변경
  df1.iloc[i,4] = int(df1.iloc[i,4].replace(',', ''))  
# 삼성전자의 모든 데이터 
for i in range(len(df2.index)):     # 모든 str -> int 변경
  for j in range(len(df2.iloc[i])):
    df2.iloc[i,j] = int(df2.iloc[i,j].replace(',', ''))  

df1 = df1.sort_values(['일자'], ascending=[True])
df2 = df2.sort_values(['일자'], ascending=[True])
print(df1)
print(df2)

                시가      고가      저가     현재가     거래량
일자                                                
2018-05-04  320.56  321.00  316.75  316.75  173911
2018-05-08  317.79  319.53  314.95  315.87  141252
2018-05-09  315.93  316.08  312.60  314.42  123610
2018-05-10  316.51  317.34  315.11  317.31  120900
2018-05-11  318.03  319.70  317.86  318.51  112400
...            ...     ...     ...     ...     ...
2020-01-23  303.77  304.72  301.71  302.33   86908
2020-01-28  294.98  296.30  291.30  292.77  130172
2020-01-29  294.38  295.67  292.45  293.98   85731
2020-01-30  293.27  294.11  287.09  288.37  101535
2020-01-31  290.24  291.47  284.53  284.53  101455

[426 rows x 5 columns]
               시가     고가     저가     종가       거래량
일자                                              
2018-05-04  53000  53900  51800  51900  39565391
2018-05-08  52600  53200  51900  52600  23104720
2018-05-09  52600  52800  50900  50900  16128305
2018-05-10  51700  51700  50600  51600  13905263
2018-05-11  52000  

## numpy를 pandas로 변경 후 저장

In [ ]:
df1 = df1.values
df2 = df2.values
print(type(df1), type(df2))
print(df1.shape, df2.shape)

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
(426, 5) (426, 5)


In [ ]:
np.save('/content/drive/My Drive/Prediction of Time Series Walking in Deep Learning/data/kospi200.npy', arr=df1)
np.save('/content/drive/My Drive/Prediction of Time Series Walking in Deep Learning/data/samsung.npy', arr=df2)

## numpy 데이터 불러오기

In [ ]:
# 오류 : ValueError: Object arrays cannot be loaded when allow_pickle=False
import numpy as np

## 먼저 기존의 np.load를 np_load_old에 저장해둠.
np_load_old = np.load

## 기존의 parameter을 바꿔줌
np.load = lambda *a,**k: np_load_old(*a, allow_pickle=True, **k)

In [ ]:
import numpy as np
import pandas as pd

kospi200 = np.load('/content/drive/My Drive/Prediction of Time Series Walking in Deep Learning/data/kospi200.npy')
samsung = np.load('/content/drive/My Drive/Prediction of Time Series Walking in Deep Learning/data/samsung.npy')

print(kospi200)
print(samsung)
print(kospi200.shape)
print(samsung.shape)

[[320.56 321.0 316.75 316.75 173911]
 [317.79 319.53 314.95 315.87 141252]
 [315.93 316.08 312.6 314.42 123610]
 ...
 [294.38 295.67 292.45 293.98 85731]
 [293.27 294.11 287.09 288.37 101535]
 [290.24 291.47 284.53 284.53 101455]]
[[53000 53900 51800 51900 39565391]
 [52600 53200 51900 52600 23104720]
 [52600 52800 50900 50900 16128305]
 ...
 [59100 59700 58800 59100 16446102]
 [58800 58800 56800 57200 20821939]
 [57800 58400 56400 56400 19749457]]
(426, 5)
(426, 5)


## DNN 구성하기

In [ ]:
def split_xy5(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column # 수정

        if y_end_number > len(dataset):  # 수정
            break
        tmp_x = dataset[i:x_end_number, :]  # 수정
        tmp_y = dataset[x_end_number:y_end_number, 3]    # 수정
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)
    
x, y = split_xy5(samsung, 5, 1) 
print(x[0,:], "\n", y[0])
print(x.shape)
print(y.shape)

[[53000 53900 51800 51900 39565391]
 [52600 53200 51900 52600 23104720]
 [52600 52800 50900 50900 16128305]
 [51700 51700 50600 51600 13905263]
 [52000 52200 51200 51300 10314997]] 
 [50100]
(421, 5, 5)
(421, 1)


### 데이터 전처리

In [ ]:
# 데이터 셋 나누기
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split( x, y, random_state=1, test_size = 0.3)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(294, 5, 5)
(127, 5, 5)
(294, 1)
(127, 1)


In [ ]:
x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1] * x_train.shape[2]))
x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1] * x_test.shape[2]))

print(x_train.shape)
print(x_test.shape)

(294, 25)
(127, 25)


In [ ]:
#### 데이터 전처리 #####
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)

x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)

print(x_train_scaled[0, :])

[ 1.13392563  1.07633086  1.02393741  0.93187013 -0.028819    1.05994459
  1.04756614  1.06686328  0.94933344  1.53138774  0.79093879  0.80213886
  0.84540479  0.81507608  0.10811605  0.73712199  0.68893234  0.71073997
  0.69657856  0.37360361  0.85647275  0.80021877  0.80910994  0.69442952
 -0.16973555]


In [ ]:
from keras.models import Sequential
from keras.layers import Dense

# 모델구성
model = Sequential()
model.add(Dense(64, input_shape=(25, )))
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1))

### 컴파일 및 훈련, 완성

In [ ]:
# 오류 : Failed to convert a NumPy array to a Tensor (Unsupported object type int).
x_train_scaled = np.asarray(x_train_scaled).astype('float32')
y_train = np.asarray(y_train).astype('float32')

model.compile(loss='mse', optimizer='adam', metrics=['mse'])

from keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(patience=20)
model.fit(x_train_scaled, y_train, validation_split=0.2, verbose=0, batch_size=1, epochs=100, callbacks=[early_stopping])

loss, mse = model.evaluate(x_test_scaled, y_test, batch_size=1)
print('loss : ', loss)
print('mse : ', mse)

127/127 [==============================] - 0s 909us/step - loss: 731050.7500 - mse: 731050.7500
loss :  731050.75
mse :  731050.75


In [ ]:
y_pred = model.predict(x_test_scaled)

for i in range(5):
    print('종가 : ', y_test[i], '/ 예측가 : ', y_pred[i])

종가 :  [52200.] / 예측가 :  [51958.367]
종가 :  [41450.] / 예측가 :  [40949.477]
종가 :  [49650.] / 예측가 :  [49372.52]
종가 :  [44800.] / 예측가 :  [45789.367]
종가 :  [49500.] / 예측가 :  [48951.07]


## LSTM 구성하기

In [ ]:
import numpy as np
import pandas as pd

kospi200 = np.load('/content/drive/My Drive/Prediction of Time Series Walking in Deep Learning/data/kospi200.npy')
samsung = np.load('/content/drive/My Drive/Prediction of Time Series Walking in Deep Learning/data/samsung.npy') 

def split_xy5(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column # 수정

        if y_end_number > len(dataset):  # 수정
            break
        tmp_x = dataset[i:x_end_number, :]  # 수정
        tmp_y = dataset[x_end_number:y_end_number, 3]    # 수정
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)
x, y = split_xy5(samsung, 5, 1) 

# 데이터 셋 나누기
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=1, test_size = 0.3)

x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1] * x_train.shape[2]))
x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1] * x_test.shape[2]))

#### 데이터 전처리 #####
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)

x_train_scaled = np.reshape(x_train_scaled, (x_train_scaled.shape[0], 5, 5))
x_test_scaled = np.reshape(x_test_scaled, (x_test_scaled.shape[0], 5, 5))

from keras.models import Sequential
from keras.layers import Dense, LSTM

# 모델구성
model = Sequential()
model.add(LSTM(64, input_shape=(5, 5)))
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1))

model.compile(loss='mse', optimizer='adam', metrics=['mse'])

from keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(patience=20)

y_train = np.asarray(y_train).astype('float32')
model.fit(x_train_scaled, y_train, validation_split=0.2, verbose=0, batch_size=1, epochs=100, callbacks=[early_stopping])

y_test = np.asarray(y_test).astype('float32')
loss, mse = model.evaluate(x_test_scaled, y_test, batch_size=1)
print('loss : ', loss)
print('mse : ', mse)

y_pred = model.predict(x_test_scaled)

for i in range(5):
    print('종가 : ', y_test[i], '/ 예측가 : ', y_pred[i])

127/127 [==============================] - 0s 1ms/step - loss: 1578468.1250 - mse: 1578468.1250
loss :  1578468.125
mse :  1578468.125
종가 :  [52200.] / 예측가 :  [53432.055]
종가 :  [41450.] / 예측가 :  [40428.016]
종가 :  [49650.] / 예측가 :  [51537.67]
종가 :  [44800.] / 예측가 :  [46305.836]
종가 :  [49500.] / 예측가 :  [50258.215]


## DNN 앙상블 구현하기

In [ ]:
import numpy as np
import pandas as pd

kospi200 = np.load('/content/drive/My Drive/Prediction of Time Series Walking in Deep Learning/data/kospi200.npy')
samsung = np.load('/content/drive/My Drive/Prediction of Time Series Walking in Deep Learning/data/samsung.npy')

def split_xy5(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column # 수정

        if y_end_number > len(dataset):  # 수정
            break
        tmp_x = dataset[i:x_end_number, :]  # 수정
        tmp_y = dataset[x_end_number:y_end_number, 3]    # 수정
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

x1, y1 = split_xy5(samsung, 5, 1) 
x2, y2 = split_xy5(kospi200, 5, 1) 

# 데이터 셋 나누기
from sklearn.model_selection import train_test_split
x1_train, x1_test, y1_train, y1_test = train_test_split(x1, y1, random_state=1, test_size = 0.3)
x2_train, x2_test, y2_train, y2_test = train_test_split(x2, y2, random_state=2, test_size = 0.3)

x1_train = np.reshape(x1_train, (x1_train.shape[0], x1_train.shape[1] * x1_train.shape[2]))
x1_test  = np.reshape(x1_test, (x1_test.shape[0], x1_test.shape[1] * x1_test.shape[2]))
x2_train = np.reshape(x2_train, (x2_train.shape[0], x2_train.shape[1] * x2_train.shape[2]))
x2_test  = np.reshape(x2_test, (x2_test.shape[0], x2_test.shape[1] * x2_test.shape[2]))

#### 데이터 전처리 #####
from sklearn.preprocessing import StandardScaler
scaler1 = StandardScaler()
scaler1.fit(x1_train)
x1_train_scaled = scaler1.transform(x1_train)
x1_test_scaled  = scaler1.transform(x1_test)

scaler2 = StandardScaler()
scaler2.fit(x2_train)
x2_train_scaled = scaler2.transform(x2_train)
x2_test_scaled  = scaler2.transform(x2_test)

from keras.models import Model
from keras.layers import Dense, Input

# 모델구성
input1  = Input(shape=(25, ))
dense1  = Dense(64)(input1)
dense1  = Dense(32)(dense1)
dense1  = Dense(32)(dense1)
output1 = Dense(32)(dense1)

input2  = Input(shape=(25, ))
dense2  = Dense(64)(input2)
dense2  = Dense(64)(dense2)
dense2  = Dense(64)(dense2)
dense2  = Dense(64)(dense2)
output2 = Dense(32)(dense2)

from keras.layers.merge import concatenate
merge   = concatenate([output1, output2])
output3 = Dense(1)(merge)

model = Model(inputs=[input1, input2], outputs = output3 )

model.compile(loss='mse', optimizer='adam', metrics=['mse'])

y1_train = np.asarray(y_train).astype('float32')
y1_test  = np.asarray(y_test).astype('float32')

from keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(patience=20)
model.fit([x1_train_scaled, x2_train_scaled], y1_train, validation_split=0.2, verbose=0, batch_size=1, epochs=100, callbacks=[early_stopping])

loss, mse = model.evaluate([x1_test_scaled, x2_test_scaled], y1_test, batch_size=1)
print('loss : ', loss)
print('mse : ', mse)

y1_pred = model.predict([x1_test_scaled, x2_test_scaled])

for i in range(5):
    print('종가 : ', y1_test[i], '/ 예측가 : ', y1_pred[i])

127/127 [==============================] - 0s 918us/step - loss: 933666.7500 - mse: 933666.7500
loss :  933666.75
mse :  933666.75
종가 :  [52200.] / 예측가 :  [51946.53]
종가 :  [41450.] / 예측가 :  [40471.004]
종가 :  [49650.] / 예측가 :  [49484.402]
종가 :  [44800.] / 예측가 :  [46415.355]
종가 :  [49500.] / 예측가 :  [48465.82]


## LSTM 앙상블 구현하기

In [ ]:
import numpy as np
import pandas as pd

kospi200 = np.load('/content/drive/My Drive/Prediction of Time Series Walking in Deep Learning/data/kospi200.npy')
samsung = np.load('/content/drive/My Drive/Prediction of Time Series Walking in Deep Learning/data/samsung.npy')

def split_xy5(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column # 수정

        if y_end_number > len(dataset):  # 수정
            break
        tmp_x = dataset[i:x_end_number, :]  # 수정
        tmp_y = dataset[x_end_number:y_end_number, 3]    # 수정
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)
x1, y1 = split_xy5(samsung, 5, 1) 
x2, y2 = split_xy5(kospi200, 5, 1) 

# 데이터 셋 나누기
from sklearn.model_selection import train_test_split
# from sklearn.model_selection import cross_val_score
x1_train, x1_test, y1_train, y1_test = train_test_split(x1, y1, random_state=1, test_size = 0.3)
x2_train, x2_test, y2_train, y2_test = train_test_split(x2, y2, random_state=2, test_size = 0.3)

y1_train = np.asarray(y_train).astype('float32')
y1_test  = np.asarray(y_test).astype('float32')

x1_train = np.reshape(x1_train, (x1_train.shape[0], x1_train.shape[1] * x1_train.shape[2]))
x1_test  = np.reshape(x1_test, (x1_test.shape[0], x1_test.shape[1] * x1_test.shape[2]))
x2_train = np.reshape(x2_train, (x2_train.shape[0], x2_train.shape[1] * x2_train.shape[2]))
x2_test  = np.reshape(x2_test, (x2_test.shape[0], x2_test.shape[1] * x2_test.shape[2]))

#### 데이터 전처리 #####
from sklearn.preprocessing import StandardScaler
scaler1 = StandardScaler()
scaler1.fit(x1_train)
x1_train_scaled = scaler1.transform(x1_train)
x1_test_scaled  = scaler1.transform(x1_test)

scaler2 = StandardScaler()
scaler2.fit(x2_train)
x2_train_scaled = scaler2.transform(x2_train)
x2_test_scaled  = scaler2.transform(x2_test)

x1_train_scaled = np.reshape(x1_train_scaled, (x1_train_scaled.shape[0], 5, 5))
x1_test_scaled  = np.reshape(x1_test_scaled, (x1_test_scaled.shape[0], 5, 5))
x2_train_scaled = np.reshape(x2_train_scaled, (x2_train_scaled.shape[0], 5, 5))
x2_test_scaled  = np.reshape(x2_test_scaled, (x2_test_scaled.shape[0], 5, 5))

from keras.models import Model
from keras.layers import Dense, Input, LSTM

# 모델구성
input1  = Input(shape=(5, 5))
dense1  = LSTM(64)(input1)
dense1  = Dense(32)(dense1)
dense1  = Dense(32)(dense1)
output1 = Dense(32)(dense1)

input2  = Input(shape=(5, 5))
dense2  = LSTM(64)(input2)
dense2  = Dense(64)(dense2)
dense2  = Dense(64)(dense2)
dense2  = Dense(64)(dense2)
output2 = Dense(32)(dense2)

from keras.layers.merge import concatenate
merge = concatenate([output1, output2])
output3 = Dense(1)(merge)

model = Model(inputs=[input1, input2], outputs = output3 )

model.compile(loss='mse', optimizer='adam', metrics=['mse'])

from keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(patience=20)
model.fit([x1_train_scaled, x2_train_scaled], y1_train, validation_split=0.2, verbose=0, batch_size=1, epochs=100, callbacks=[early_stopping])

loss, mse = model.evaluate([x1_test_scaled, x2_test_scaled], y1_test, batch_size=1)
print('loss : ', loss)
print('mse : ', mse)

y1_pred = model.predict([x1_test_scaled, x2_test_scaled])

for i in range(5):
    print('종가 : ', y1_test[i], '/ 예측가 : ', y1_pred[i])

127/127 [==============================] - 0s 1ms/step - loss: 3256463.7500 - mse: 3256463.7500
loss :  3256463.75
mse :  3256463.75
종가 :  [52200.] / 예측가 :  [54517.156]
종가 :  [41450.] / 예측가 :  [42135.41]
종가 :  [49650.] / 예측가 :  [51854.504]
종가 :  [44800.] / 예측가 :  [47931.477]
종가 :  [49500.] / 예측가 :  [52563.805]
